services: 
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_NAME}
    container_name: teslodb  # Nombre del contenedor
    volumes:
      - ./postgres:/var/lib/postgresql/data
    